-- MySQL Script generated by MySQL Workbench
-- Mon Jun 29 15:39:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `optica` ;

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica` DEFAULT CHARACTER SET utf8 ;
USE `optica` ;

-- -----------------------------------------------------
-- Table `optica`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `optica`.`clients` ;

CREATE TABLE IF NOT EXISTS `optica`.`clients` (
  `id_client` INT UNSIGNED NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `cp` INT(10) UNSIGNED ZEROFILL NULL DEFAULT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefon` INT UNSIGNED NULL DEFAULT NULL,
  `entrada` ENUM('anuncis', 'conegut', 'internet') NOT NULL,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `optica`.`proveidor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `optica`.`proveidor` ;

CREATE TABLE IF NOT EXISTS `optica`.`proveidor` (
  `nif` INT UNSIGNED NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `carrer` VARCHAR(45) NOT NULL,
  `numero` INT UNSIGNED NOT NULL,
  `pis` INT UNSIGNED NOT NULL,
  `porta` INT UNSIGNED NOT NULL,
  `ciutat` VARCHAR(45) NOT NULL,
  `cp` INT(10) UNSIGNED ZEROFILL NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `telefon` INT UNSIGNED NOT NULL,
  `fax` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`nif`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `optica`.`marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `optica`.`marca` ;

CREATE TABLE IF NOT EXISTS `optica`.`marca` (
  `nom` VARCHAR(45) NOT NULL,
  `proveidor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`nom`),
  INDEX `foranaproveidor` (`proveidor` ASC) VISIBLE,
  CONSTRAINT `foranaproveidor`
    FOREIGN KEY (`proveidor`)
    REFERENCES `optica`.`proveidor` (`nif`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `optica`.`ulleres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `optica`.`ulleres` ;

CREATE TABLE IF NOT EXISTS `optica`.`ulleres` (
  `model` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `graduacio` FLOAT UNSIGNED NOT NULL,
  `montura` ENUM('flotant', 'pasta', 'metalica') NOT NULL,
  `color` ENUM('negres', 'blanques', 'marrons') NOT NULL,
  `vidreDret` ENUM('transparent', 'opac') NOT NULL,
  `vidreEsquerra` ENUM('transparent', 'opac') NOT NULL,
  `preu` FLOAT UNSIGNED NOT NULL,
  PRIMARY KEY (`model`),
  INDEX `foranamarca` (`marca` ASC) VISIBLE,
  CONSTRAINT `foranamarca`
    FOREIGN KEY (`marca`)
    REFERENCES `optica`.`marca` (`nom`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `optica`.`venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `optica`.`venta` ;

CREATE TABLE IF NOT EXISTS `optica`.`venta` (
  `id_venta` INT UNSIGNED NOT NULL,
  `ulleres` VARCHAR(45) NOT NULL,
  `client_id` INT UNSIGNED NOT NULL,
  `empleat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_venta`),
  INDEX `foranaulleres` (`ulleres` ASC) VISIBLE,
  INDEX `foranaclient` (`client_id` ASC) VISIBLE,
  CONSTRAINT `foranaclient`
    FOREIGN KEY (`client_id`)
    REFERENCES `optica`.`clients` (`id_client`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `foranaulleres`
    FOREIGN KEY (`ulleres`)
    REFERENCES `optica`.`ulleres` (`model`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
